apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "oauth2-proxy-themed.name" . }}
    chart: {{ template "oauth2-proxy-themed.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "oauth2-proxy-themed.fullname" . }}-assets
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ template "oauth2-proxy-themed.name" . }}
    chart: {{ template "oauth2-proxy-themed.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
